var applyJson = 
{ jobPost:
   { jobPostId: '57d54f1db4490e71ee6107ad',
     employer:
      { employerId: '57d5529ab4490e71f5379e09',
        user:
         { userID: 5069081,
           name:
            { firstName: 'Sripad',
              lastName: '',
              salutation: 'MR',
              middleName: null } },
        organisation: { name: 'Surabhi Ventures' } },
     jobCategory: { id: 14, name: 'Cashier/Retail', synonyms: [] },
     title: 'Retail Sales Executive',
     createdOn: '2016-08-31T19:01:17.817Z',
     modifiedOn: '2016-09-01T11:37:21.707Z',
     validUntil: '2016-11-29T00:00:00Z',
     benefits: null,
     description: 'Experience in retail sales in a showroom or a super market, especially in a baby and kids showroom will be an added advantage.',
     salary:
      { attributeId: 262,
        attributeName: 'CurrentSalary',
        attributeType: 'SingleValue',
        dataType: 'Number',
        classification: 'Profile',
        value: 10000 },
     address:
      { addressId: null,
        premise: null,
        route: null,
        landmark: '',
        sublocality_level_1: 'T Dasarahalli',
        sublocality_level_2: null,
        locality: 'Bangalore',
        administrative_area_level_1: null,
        administrative_area_level_2: null,
        country: 'India',
        postal_code: '560057',
        location: { latitude: 13.0429056, longitude: 77.5131504 },
        formatted_address: null,
        address_line_1: null,
        address_line_2: null,
        confidence: 100 },
     jobRequirements:
      [ { requirementId: null,
          questionId: 2522,
          requirementType: 1,
          attributeId: 77,
          attributeName: 'TypeofSalesExp',
          attributeType: 'MultiValue',
          dataType: 'Skill',
          classification: 'Experience',
          value:
           [ { name: 'Counter Sales or Retail Sales',
               id: 8,
               answerOptionId: 5634 } ] },
        { requirementId: null,
          questionId: 2526,
          requirementType: 1,
          attributeId: 80,
          attributeName: 'CashierTools',
          attributeType: 'MultiValue',
          dataType: 'Skill',
          classification: 'Experience',
          value:
           [ { name: 'Cash Register', id: 1, answerOptionId: 5644 },
             { name: 'Billing software', id: 2, answerOptionId: 5645 } ] },
        { requirementId: null,
          questionId: 2563,
          requirementType: 1,
          attributeId: 116,
          attributeName: 'FinanceExp',
          attributeType: 'MultiValue',
          dataType: 'Default',
          classification: 'Experience',
          value:
           [ { value: 'Cash Register', id: 1, answerOptionId: 5793 },
             { value: 'Billing software', id: 2, answerOptionId: 5794 } ] },
        { requirementId: null,
          questionId: 2580,
          requirementType: 1,
          attributeId: 133,
          attributeName: 'SpokenLanguages',
          attributeType: 'MultiValue',
          dataType: 'Language',
          classification: 'Profile',
          value: [ { name: 'Kannada', id: 6, code: 'kn', answerOptionId: 5868 } ] },
        { requirementId: null,
          questionId: 2608,
          requirementType: 1,
          attributeId: 161,
          attributeName: 'SchoolCertificates',
          attributeType: 'MultiValue',
          dataType: 'Document',
          classification: 'Qualification',
          value: [ { name: '10th', id: 1, answerOptionId: 6016 } ] },
        { requirementId: null,
          questionId: 1956,
          requirementType: 1,
          attributeId: 10,
          attributeName: 'ComputerKnowledge',
          attributeType: 'SingleValue',
          dataType: 'Default',
          classification: 'Skill',
          value: { value: 'Yes', id: 1, answerOptionId: 4374 } },
        { requirementId: null,
          questionId: 1957,
          requirementType: 1,
          attributeId: 11,
          attributeName: 'CounterSalesType',
          attributeType: 'MultiValue',
          dataType: 'Skill',
          classification: 'Experience',
          value: [ { name: 'Retail store', id: 1, answerOptionId: 4376 } ] } ],
     report: null,
     rseUserIds: null,
     status: 2,
     plan:
      { planId: '1',
        name: 'Free Post',
        description: 'Post a job for free. No phone no. access',
        price:
         { basePrice: 0,
           serviceTax: 0,
           swatchBharatCessTax: 0.5,
           totalPrice: 0 },
        numberOfUnlocks: 0,
        planType: 0 },
     totalNumberOfOpenings: 4,
     currentVacancies: 4,
     actions: null,
     totalAllowedUnlocks: 0,
     hasActiveCampaigns: false,
     isPromoted: null,
     timing: { startTime: '09:00:00', duration: 8 },
     createdById: '5069081',
     jobId: 2146293054,
     modifiedById: '3945676',
     approvedBy: null,
     approvalType: null,
     rejectedBy: null,
     rejectionReason: null,
     deactivatedBy: null,
     callConnectEnabled: true,
     previousStatus: 6 },
  jobApplicationId: '41330583',
  jobSeekerId: '8061623',
  jobPostId: '57d54f1db4490e71ee6107ad',
  employerId: '5069081',
  answers:
   [ { questionId: 1957,
       questionText: 'What type of counter sales experience do you have?',
       options:
        [ { id: 1,
            answerOptionId: 4376,
            name: 'Retail store',
            expertise: 0,
            confidence: 0,
            labelSeeker: 'Has Retail store sales experience',
            labelPost: 'Retail store sales experience required',
            has: false },
          { id: 2,
            answerOptionId: 4377,
            name: 'Showroom',
            expertise: 0,
            confidence: 0,
            labelSeeker: 'Has Showroom Sales Experience',
            labelPost: 'Showroom Sales Experience Needed',
            has: false },
          { id: 3,
            answerOptionId: 4378,
            name: 'Restaurant or Cafe',
            expertise: 0,
            confidence: 0,
            labelSeeker: 'Has Restaurant Sales Experience',
            labelPost: 'Restaurant Sales Experience Needed',
            has: false } ],
       attributeId: 11,
       attributeName: 'CounterSalesType',
       attributeType: 'MultiValue',
       dataType: 'Skill',
       classification: 'Experience' },
     { questionId: 2522,
       questionText: 'What type of Sales experience do you have?',
       options:
        [ { id: 1,
            answerOptionId: 5627,
            name: 'Tele Sales',
            expertise: 0,
            confidence: 0,
            labelSeeker: 'Has Tele Sales',
            labelPost: 'Need Tele Sales',
            has: false },
          { id: 2,
            answerOptionId: 5628,
            name: 'Online Sales',
            expertise: 0,
            confidence: 0,
            labelSeeker: 'Has Online Sales',
            labelPost: 'Need Online Sales',
            has: false },
          { id: 3,
            answerOptionId: 5629,
            name: 'Industrial Sales',
            expertise: 0,
            confidence: 0,
            labelSeeker: 'Has Industrial Sales',
            labelPost: 'Need Industrial Sales',
            has: false },
          { id: 4,
            answerOptionId: 5630,
            name: 'IT Sales',
            expertise: 0,
            confidence: 0,
            labelSeeker: 'Has IT Sales',
            labelPost: 'Need IT Sales',
            has: false },
          { id: 5,
            answerOptionId: 5631,
            name: 'Field Sales',
            expertise: 0,
            confidence: 0,
            labelSeeker: 'Has Field Sales',
            labelPost: 'Need Field Sales',
            has: false },
          { id: 6,
            answerOptionId: 5632,
            name: 'Enterprise sales',
            expertise: 0,
            confidence: 0,
            labelSeeker: 'Has Enterprise sales',
            labelPost: 'Need Enterprise sales',
            has: false },
          { id: 7,
            answerOptionId: 5633,
            name: 'Door to door sales',
            expertise: 0,
            confidence: 0,
            labelSeeker: 'Knows Door to door sales',
            labelPost: 'Need Door to door sales',
            has: false },
          { id: 8,
            answerOptionId: 5634,
            name: 'Counter Sales or Retail Sales',
            expertise: 0,
            confidence: 0,
            labelSeeker: 'Knows Counter Sales or Retail Sales',
            labelPost: 'Need Counter Sales or Retail Sales',
            has: false },
          { id: 9,
            answerOptionId: 5635,
            name: 'Corporate Sales',
            expertise: 0,
            confidence: 0,
            labelSeeker: 'Knows Corporate Sales',
            labelPost: 'Need Corporate Sales',
            has: false } ],
       attributeId: 77,
       attributeName: 'TypeofSalesExp',
       attributeType: 'MultiValue',
       dataType: 'Skill',
       classification: 'Experience' },
     { questionId: 2526,
       questionText: 'Which of the following have you used?',
       options:
        [ { id: 1,
            answerOptionId: 5644,
            name: 'Cash Register',
            expertise: 0,
            confidence: 0,
            labelSeeker: 'Used Cash Register',
            labelPost: 'Used Cash Register',
            has: false },
          { id: 2,
            answerOptionId: 5645,
            name: 'Billing software',
            expertise: 0,
            confidence: 0,
            labelSeeker: 'Knows Billing software Experience',
            labelPost: 'Knows Billing software Experience',
            has: false },
          { id: 3,
            answerOptionId: 5646,
            name: 'MIS-Excel',
            expertise: 0,
            confidence: 0,
            labelSeeker: 'Used MIS-Excel',
            labelPost: 'Used MIS-Excel',
            has: false } ],
       attributeId: 80,
       attributeName: 'CashierTools',
       attributeType: 'MultiValue',
       dataType: 'Skill',
       classification: 'Experience' },
     { questionId: 2563,
       questionText: 'Which of the following have you worked on?',
       options:
        [ { id: 1,
            value: 'Cash Register',
            answerOptionId: 5793,
            labelSeeker: 'Worked on Cash Register',
            labelPost: 'Work on Cash Register',
            has: false },
          { id: 2,
            value: 'Billing software',
            answerOptionId: 5794,
            labelSeeker: 'Worked on Billing software',
            labelPost: 'Worke on Billing software',
            has: false },
          { id: 3,
            value: 'Excel',
            answerOptionId: 5795,
            labelSeeker: 'Worked on Excel',
            labelPost: 'Work on Excel',
            has: false },
          { id: 4,
            value: 'Tally',
            answerOptionId: 5796,
            labelSeeker: 'Worked on Tally',
            labelPost: 'Work on Tally',
            has: false } ],
       attributeId: 116,
       attributeName: 'FinanceExp',
       attributeType: 'MultiValue',
       dataType: 'Default',
       classification: 'Experience' },
     { questionId: 1956,
       questionText: 'Are you familiar with applications like Microsoft Office & Internet Explorer?',
       options:
        [ { id: 1,
            value: 'Yes',
            answerOptionId: 4374,
            labelSeeker: 'Has Basic Computer Knowledge',
            labelPost: 'Need Basic Computer Knowledge' },
          { id: 2, value: 'No', answerOptionId: 4375 } ],
       attributeId: 10,
       attributeName: 'ComputerKnowledge',
       attributeType: 'SingleValue',
       dataType: 'Default',
       classification: 'Skill' },
     { questionId: 2608,
       questionText: 'Which of the following school certificates do you have?',
       options:
        [ { id: 1,
            answerOptionId: 6016,
            uploaded: 'yes',
            name: '10th',
            isVerified: false,
            has: false,
            confidence: 0 },
          { id: 2,
            answerOptionId: 6017,
            uploaded: 'yes',
            name: '12th',
            isVerified: false,
            has: false,
            confidence: 0 },
          { id: 3,
            answerOptionId: 6018,
            uploaded: 'yes',
            name: 'PUC',
            isVerified: false,
            has: false,
            confidence: 0 },
          { id: 4,
            answerOptionId: 6019,
            uploaded: 'yes',
            name: 'Diploma',
            isVerified: false,
            has: false,
            confidence: 0 } ],
       attributeId: 161,
       attributeName: 'SchoolCertificates',
       attributeType: 'MultiValue',
       dataType: 'Document',
       classification: 'Qualification' },
     { questionId: 2580,
       questionText: 'Which of the following languages can you speak?',
       options:
        [ { id: 3,
            name: 'English',
            answerOptionId: 5866,
            labelSeeker: 'Know English',
            labelPost: 'Knows English',
            has: false },
          { id: 5,
            name: 'Hindi',
            answerOptionId: 5867,
            labelSeeker: 'Know Hindi',
            labelPost: 'Knows Hindi',
            has: false },
          { id: 6,
            name: 'Kannada',
            answerOptionId: 5868,
            labelSeeker: 'Know Kannada',
            labelPost: 'Knows Kannada',
            has: false },
          { id: 12,
            name: 'Tamil',
            answerOptionId: 5869,
            labelSeeker: 'Know Tamil',
            labelPost: 'Knows Tamil',
            has: false },
          { id: 13,
            name: 'Telugu',
            answerOptionId: 5870,
            labelSeeker: 'Know Telugu',
            labelPost: 'Knows Telugu',
            has: false },
          { id: 8,
            name: 'Malayalam',
            answerOptionId: 5871,
            labelSeeker: 'Know Malayalam',
            labelPost: 'Knows Malayalam',
            has: false },
          { id: 1,
            name: 'Bengali',
            answerOptionId: 5872,
            labelSeeker: 'Know Bengali',
            labelPost: 'Knows Bengali',
            has: false },
          { id: 4,
            name: 'Gujarati',
            answerOptionId: 5873,
            labelSeeker: 'Know Gujarati',
            labelPost: 'Knows Gujarati',
            has: false },
          { id: 9,
            name: 'Marathi',
            answerOptionId: 5874,
            labelSeeker: 'Know Marathi',
            labelPost: 'Knows Marathi',
            has: false },
          { id: 14,
            name: 'Urdu',
            answerOptionId: 5875,
            labelSeeker: 'Know Urdu',
            labelPost: 'Knows Urdu',
            has: false },
          { id: 10,
            name: 'Odiya',
            answerOptionId: 5876,
            labelSeeker: 'Know Odiya',
            labelPost: 'Knows Odiya',
            has: false },
          { id: 11,
            name: 'Punjabi',
            answerOptionId: 5877,
            labelSeeker: 'Know Punjabi',
            labelPost: 'Knows Punjabi',
            has: false },
          { id: 15,
            name: 'Assamese',
            answerOptionId: 5878,
            labelSeeker: 'Know Assamese',
            labelPost: 'Knows Assamese',
            has: false } ],
       attributeId: 133,
       attributeName: 'SpokenLanguages',
       attributeType: 'MultiValue',
       dataType: 'Language',
       classification: 'Profile' } ],
  status: 'Applied',
  applicationDate: '2016-11-10T16:21:49.65Z',
  modifiedOnDate: '2016-11-10T16:21:49.65Z',
  score: 0,
  notes: '',
  rseUser:
  {
    userID: -1,
    
     name:
      { firstName: '',
        lastName: '',
        salutation: 'MR',
        middleName: null },
     dateOfBirth: '0001-01-01T00:00:00',
     contactDetails: null,
     role: 'RSE',
     gender: 'Unspecified',
     profilePicture: null,
     createdBy: null,
     preferredLanguage: null,
     aboutMe: null,
     lastSignIn: '0001-01-01T00:00:00',
     createdOn: '0001-01-01T00:00:00',
     facebookProfile: null,
     linkedInProfile: null,
     googleProfile: null },
  distance: 0,
  isUnlocked: false,
  actions: { withdrawn: '/jobApplications/41330583/status/Withdrawn' } }
